spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  application:
    name: aegis
  datasource:
    url: jdbc:mysql://database-2.cry282ck8zvl.us-east-2.rds.amazonaws.com/aegis
    username: tony
    password: qoS4SrdVMuxxbUUGK93s
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: 74.207.241.208
      port: 6379
      password: 5f6e7d8c9b0a1b2c3d4e5f6071827364
      timeout: 5000
  mail:
    host: smtp.gmail.com
    port: 587
    username: aegiscyberalert@gmail.com
    password: obkhjmwcnvcvixkv
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


aes:
  key: 8fR2kV7a3NqNdbEud10zBTPv
server:
  port: 8080

astra:
  token: AstraCS:fxpNCpzJFbkDCuulJjiEALNn:d9b171f83cb7af9a2c5de4db20f2f2797fc4f1539afee8ca5bb450ac4a0f6c96

CRAWLER_URL: http://localhost:5001/vulns