spring:
  application:
    name: aegis
  datasource:
    url: jdbc:mysql://database-2.cry282ck8zvl.us-east-2.rds.amazonaws.com
    username: tony
    password: qoS4SrdVMuxxbUUGK93s
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
aes:
  key:
server:
  port: 8080