version: '3.8'

services:
  backend:
    build: ./Aegis-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - crawler

  crawler:
    build: ./Webscraping/vuln_scrape
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080

networks:
  app-network:
    driver: bridge
