version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - NODE_ENV=production

  backend:
    build: ./Aegis-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - crawler
    environment:
      - CRAWLER_URL=http://crawler:5001/vulns
    extra_hosts:
      - "host.docker.internal:host-gateway"

  crawler:
    build: ./Webscraping/crawler
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
